/*
* generated by Xtext
*/
package be.kuleuven.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RFSMUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return be.kuleuven.dsl.ui.internal.RFSMActivator.getInstance().getInjector("be.kuleuven.dsl.RFSM");
	}
	
}
