/*
 * generated by Xtext
 */
package be.kuleuven.dsl.ui.contentassist

import be.kuleuven.dsl.ui.contentassist.AbstractRFSMProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RFSMProposalProvider extends AbstractRFSMProposalProvider {
}
