/*
* generated by Xtext
*/
package be.kuleuven.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.kuleuven.dsl.services.RFSMGrammarAccess;

public class RFSMParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RFSMGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.kuleuven.dsl.parser.antlr.internal.InternalRFSMParser createParser(XtextTokenStream stream) {
		return new be.kuleuven.dsl.parser.antlr.internal.InternalRFSMParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RfsmGraph";
	}
	
	public RFSMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RFSMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
