/*
 * generated by Xtext
 */
package be.kuleuven.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RFSMRuntimeModule extends be.kuleuven.dsl.AbstractRFSMRuntimeModule {

}
