/*
* generated by Xtext
*/
package be.kuleuven.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RFSMStandaloneSetup extends RFSMStandaloneSetupGenerated{

	public static void doSetup() {
		new RFSMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

