/*
 * generated by Xtext
 */
package be.kuleuven.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RFSMUiModule extends be.kuleuven.dsl.ui.AbstractRFSMUiModule {
	public RFSMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
