/**
 * generated by Xtext
 */
package be.kuleuven.dsl.validation;

import be.kuleuven.dsl.validation.AbstractRFSMValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RFSMValidator extends AbstractRFSMValidator {
}
