/*
 * generated by Xtext
 */
package be.kuleuven.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import be.kuleuven.dsl.ui.internal.RFSMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RFSMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RFSMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RFSMActivator.getInstance().getInjector(RFSMActivator.BE_KULEUVEN_DSL_RFSM);
	}
	
}
